export const SEARCH_CATEGORIES = [
  { title: 'Restaurants', alias: 'restaurants', search_term: 'restaurants', icon: 'fa-utensils' },
  { title: 'Delivery', alias: 'delivery', search_term: 'delivery', icon: 'fa-bicycle' },
  { title: 'Takeout', alias: 'takeout', search_term: 'takeout', icon: 'fa-shopping-bag' },
  { title: 'Accountants', alias: 'accountants', search_term: 'accountants', icon: 'fa-calculator' },
  { title: 'Plumbers', alias: 'plumbers', search_term: 'plumbers', icon: 'fa-toolbox' },
  { title: 'Auto Repair', alias: 'autorepair', search_term: 'auto+repair', icon: 'fa-wrench' },
];

export const SEARCH_CATEGORY_TYPES = [
  { title: 'Accounting', type: 'accounting' },
  { title: 'Airport', type: 'airport' },
  { title: 'Amusement Park', type: 'amusement_park' },
  { title: 'Aquarium', type: 'aquarium' },
  { title: 'Art Gallery', type: 'art_gallery' },
  { title: 'ATM', type: 'atm' },
  { title: 'Bakery', type: 'bakery' },
  { title: 'Bank', type: 'bank' },
  { title: 'Bar', type: 'bar' },
  { title: 'Beauty Salon', type: 'beauty_salon' },
  { title: 'Bicycle Store', type: 'bicycle_store' },
  { title: 'Book Store', type: 'book_store' },
  { title: 'Bowling Alley', type: 'bowling_alley' },
  { title: 'Bus Station', type: 'bus_station' },
  { title: 'Cafe', type: 'cafe' },
  { title: 'Campground', type: 'campground' },
  { title: 'Car Dealer', type: 'car_dealer' },
  { title: 'Car Rental', type: 'car_rental' },
  { title: 'Car Repair', type: 'car_repair' },
  { title: 'Car Wash', type: 'car_wash' },
  { title: 'Casino', type: 'casino' },
  { title: 'Cemetary', type: 'cemetery' },
  { title: 'Church', type: 'church' },
  { title: 'City Hall', type: 'city_hall' },
  { title: 'Clothing Store', type: 'clothing_store' },
  { title: 'Convenience Store', type: 'convenience_store' },
  { title: 'Courthouse', type: 'courthouse' },
  { title: 'Dentist', type: 'dentist' },
  { title: 'Department Store', type: 'department_store' },
  { title: 'Doctor', type: 'doctor' },
  { title: 'Drugstore', type: 'drugstore' },
  { title: 'Electrician', type: 'electrician' },
  { title: 'Electronics Store', type: 'electronics_store' },
  { title: 'Embassy', type: 'embassy' },
  { title: 'Fire Station', type: 'fire_station' },
  { title: 'Florist', type: 'florist' },
  { title: 'Funeral Home', type: 'funeral_home' },
  { title: 'Furniture Store', type: 'furniture_store' },
  { title: 'Gas Station', type: 'gas_station' },
  { title: 'Gym', type: 'gym' },
  { title: 'Hair Care', type: 'hair_care' },
  { title: 'Hardware Store', type: 'hardware_store' },
  { title: 'Hindu Temple', type: 'hindu_temple' },
  { title: 'Home Goods Store', type: 'home_goods_store' },
  { title: 'Hospital', type: 'hospital' },
  { title: 'Insurance Agency', type: 'insurance_agency' },
  { title: 'Jewelry Store', type: 'jewelry_store' },
  { title: 'Laundry', type: 'laundry' },
  { title: 'Lawyer', type: 'lawyer' },
  { title: 'Library', type: 'library' },
  { title: 'Light Rail Station', type: 'light_rail_station' },
  { title: 'Liquor Store', type: 'liquor_store' },
  { title: 'Local Government Office', type: 'local_government_office' },
  { title: 'Locksmith', type: 'locksmith' },
  { title: 'Lodging', type: 'lodging' },
  { title: 'Meal Delivery', type: 'meal_delivery' },
  { title: 'Meal Takeaway', type: 'meal_takeaway' },
  { title: 'Mosque', type: 'mosque' },
  { title: 'Movie Rental', type: 'movie_rental' },
  { title: 'Movie Theater', type: 'movie_theater' },
  { title: 'Moving Company', type: 'moving_company' },
  { title: 'Museum', type: 'museum' },
  { title: 'Night Club', type: 'night_club' },
  { title: 'Painter', type: 'painter' },
  { title: 'Park', type: 'park' },
  { title: 'Parking', type: 'parking' },
  { title: 'Pet Store', type: 'pet_store' },
  { title: 'Pharmacy', type: 'pharmacy' },
  { title: 'Physiotherapist', type: 'physiotherapist' },
  { title: 'Plumber', type: 'plumber' },
  { title: 'Police', type: 'police' },
  { title: 'Post Office', type: 'post_office' },
  { title: 'Primary School', type: 'primary_school' },
  { title: 'Real Estate Agency', type: 'real_estate_agency' },
  { title: 'Restaurant', type: 'restaurant' },
  { title: 'Roofing Contractor', type: 'roofing_contractor' },
  { title: 'RV Park', type: 'rv_park' },
  { title: 'School', type: 'school' },
  { title: 'Secondary School', type: 'secondary_school' },
  { title: 'Shoe Store', type: 'shoe_store' },
  { title: 'Shopping Mall', type: 'shopping_mall' },
  { title: 'Spa', type: 'spa' },
  { title: 'Stadium', type: 'stadium' },
  { title: 'Storage', type: 'storage' },
  { title: 'Store', type: 'store' },
  { title: 'Subway Station', type: 'subway_station' },
  { title: 'Supermarket', type: 'supermarket' },
  { title: 'Synagogue', type: 'synagogue' },
  { title: 'Taxi Stand', type: 'taxi_stand' },
  { title: 'Tourist Attraction', type: 'tourist_attraction' },
  { title: 'Train Station', type: 'train_station' },
  { title: 'Transit Station', type: 'transit_station' },
  { title: 'Travel Agency', type: 'travel_agency' },
  { title: 'University', type: 'university' },
  { title: 'Veterinary Care', type: 'veterinary_care' },
  { title: 'Zoo', type: 'zoo' },
]
